name: Amazon Price Tracker

on:
  schedule:
    # Runs every 2 hours (adjust as needed)
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Set up environment variables
        env:
          PRODUCT_URL: ${{ secrets.PRODUCT_URL }}
          THRESHOLD_PRICE: ${{ secrets.THRESHOLD_PRICE }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          LOG_FILE: price_log.txt
          CSV_FILE: price_log.csv
        run: |
          echo "Environment variables set."

      - name: Run price tracker
        run: python webscrapper.py --once

      - name: Upload price log CSV
        uses: actions/upload-artifact@v4
        with:
          name: pricelog
          path: price_log.csv
